name: Deploy React to GCS

on:
  push:
    branches:
      - main # Deploy on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install gsutil
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli

      - name: Check gsutil
        run: gsutil version

      - name: Deploy to GCS
        run: |
          gsutil -m rsync -r build gs://design_app_bucket
          gsutil web set -m index.html -e 404.html gs://design_app_bucket
